/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCompetencesRouteImport } from './routes/dashboard.competences'
import { Route as DashboardJournalRouteImport } from './routes/dashboard.journal'
import { Route as DashboardProfilRouteImport } from './routes/dashboard.profil'
import { Route as DashboardRapportsRouteImport } from './routes/dashboard.rapports'
import { Route as DashboardTachesRouteImport } from './routes/dashboard.taches'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetencesRoute = DashboardCompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJournalRoute = DashboardJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfilRoute = DashboardProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRapportsRoute = DashboardRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTachesRoute = DashboardTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => DashboardRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/competences': typeof DashboardCompetencesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/taches': typeof DashboardTachesRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/competences': typeof DashboardCompetencesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/taches': typeof DashboardTachesRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/competences': typeof DashboardCompetencesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/profil': typeof DashboardProfilRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/taches': typeof DashboardTachesRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/dashboard/competences'
    | '/dashboard/journal'
    | '/dashboard/profil'
    | '/dashboard/rapports'
    | '/dashboard/taches'
    | '/reset-password/$token'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/dashboard/competences'
    | '/dashboard/journal'
    | '/dashboard/profil'
    | '/dashboard/rapports'
    | '/dashboard/taches'
    | '/reset-password/$token'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/dashboard/competences'
    | '/dashboard/journal'
    | '/dashboard/profil'
    | '/dashboard/rapports'
    | '/dashboard/taches'
    | '/reset-password/$token'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competences': {
      id: '/dashboard/competences'
      path: '/competences'
      fullPath: '/dashboard/competences'
      preLoaderRoute: typeof DashboardCompetencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journal': {
      id: '/dashboard/journal'
      path: '/journal'
      fullPath: '/dashboard/journal'
      preLoaderRoute: typeof DashboardJournalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profil': {
      id: '/dashboard/profil'
      path: '/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof DashboardProfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rapports': {
      id: '/dashboard/rapports'
      path: '/rapports'
      fullPath: '/dashboard/rapports'
      preLoaderRoute: typeof DashboardRapportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/taches': {
      id: '/dashboard/taches'
      path: '/taches'
      fullPath: '/dashboard/taches'
      preLoaderRoute: typeof DashboardTachesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCompetencesRoute: typeof DashboardCompetencesRoute
  DashboardJournalRoute: typeof DashboardJournalRoute
  DashboardProfilRoute: typeof DashboardProfilRoute
  DashboardRapportsRoute: typeof DashboardRapportsRoute
  DashboardTachesRoute: typeof DashboardTachesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCompetencesRoute: DashboardCompetencesRoute,
  DashboardJournalRoute: DashboardJournalRoute,
  DashboardProfilRoute: DashboardProfilRoute,
  DashboardRapportsRoute: DashboardRapportsRoute,
  DashboardTachesRoute: DashboardTachesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
